### ISSUE TITLE
Question Regarding License Compliance with readline

### ISSUE THREAD

**Issue by SARDONYX-sard** [TartanLlama/sdb#1]
Hello,

First of all, thank you for this fantastic repository! I have been reading through the source code for learning purposes, and I came across a question regarding the licenses of the dependencies, which is why I decided to open this issue (as it doesn't seem to fit any of the existing issue templates, I am using a blank issue).

I noticed that the readline library, which is under the GPL license, is being used. However, the LICENSE.txt in this repository states that the project is under the MIT license. I apologize if this causes any inconvenience, but I was concerned that this might potentially result in a license violation.

Here is the link to the readline package on vcpkg:
[vcpkg readline](https://vcpkg.io/en/package/readline)

Thank you for your time.

**Comment by TartanLlama** [comment]
You're right, thanks for raising this. For some reason I though readline
was LGPL licensed. I need to think about how to best resolve this.

**Comment by TartanLlama** [comment]
I don't particularly want to force readers to GPL license their code, so I think the best thing is for me to change to linenoise as a dependency. So first step is to get that added to vcpkg, then change the code and update the book.

**Comment by SARDONYX-sard** [comment]
I agree. I am glad I could be of help.

**Comment by TartanLlama** [comment]
Guh, linenoise doesn't support programmatically reading the history, and linenoise-ng does, but in a kinda broken way. Guess I need to use libedit instead

**Comment by TartanLlama** [comment]
I've created a PR to add libedit to vpckg: https://github.com/microsoft/vcpkg/pull/41442

**Comment by TartanLlama** [comment]
This is now fixed: the codebase and latest book draft use `libedit` rather than `readline`
