### ISSUE TITLE
Didn't see `y`'s in Charpter 3's manually testing

### ISSUE THREAD

**Issue by WenqingZong** [TartanLlama/sdb#3]
Hello, 

Thank you for this amazing book, it taught me a lot already although I've only done the first two chapters. 

I do encounter a problem while following your code in Chapter 3. 
![image](https://github.com/user-attachments/assets/5b266c3b-69d3-43e3-8242-aae53619812f)

Here, I cannot see any `y`s in terminal output. 
<img width="484" alt="image" src="https://github.com/user-attachments/assets/bcd21673-4393-4007-bf95-dd62f862bc9a">

I've checked my code for several times and I believe they match your implementation in the book. It could be my environment problem but I'm not 100% sure. 

My environment: 
Physics machine: MacBook Air with M2 Chip
Editor: VSCode + devcontainer
Docker image: `ubuntu:latest` and runs on platform `linux/amd64`

You can see my probably-buggy code at this [commit](https://github.com/WenqingZong/sdb/commit/c0c37c5e8abce757e94717c162dab91c7e1c5ed4). 

Just wanna raise this small problem here so I can continue reading the rest of the book. I've already wasted two nights debugging this but gain nothing. Really eager to finish my own debugger :-).

Regards,
And thank you again for this wonderful book.

**Comment by TartanLlama** [comment]
Thanks for getting in touch! I'll have a look at your code and see if I can find any issues

**Comment by TartanLlama** [comment]
Running through WSL I don't see any issues, so it must be an environment problem

**Comment by TartanLlama** [comment]
Have you tried using a [UTM virtual machine](https://mac.getutm.app/) instead of Docker? I'll have a play around with Docker on Windows to see if I can repro the issue

**Comment by TartanLlama** [comment]
It works through Docker on Windows for me, it must be a Mac thing

**Comment by TartanLlama** [comment]
Can you try installing x64 Ubuntu on a UTM virtual machine and see if that works?

**Comment by WenqingZong** [comment]
Spent another night installing Ubuntu in UTM, enumerate mood is so slow in every operation. I'll update you later when I get something.

**Comment by corrosive4354** [comment]
You mentioned that you are using Docker and VSCode development containers. Please make sure that your Docker environment is configured correctly and there are no restrictions affecting the output. You can try running the code in the local environment to see if the output is normal.

Seeing that you are using Docker, I would like to recommend [Servbay](https://servbay.com) to you, which is more professional and easy to use than Docker on Mac

**Comment by WenqingZong** [comment]
Hi, sorry for the late reply. 

I didn't managed to install UTM VM, it always fail (after a LOOOOONG processing time) due to various errors and I just got angry with the env things. I bought another x86_64 computer instead and the same code just works as expected. 

I may come back to Mac + docker/UTM months later but now I just transfer my workflow to the native x86_64 PC. It's way more easier and time saving.

**Comment by TartanLlama** [comment]
Thanks for following up, I'm going to add some text to the intro of the book about this environment issue
