### ISSUE TITLE
Errata: Chapter 4 process::resume already terminated test always fails

### ISSUE THREAD

**Issue by tmcgilchrist** [TartanLlama/sdb#4]
**Chapter:** 4
**Description:** The process already terminated test always fails.
**Reproduction steps:** Running Ubuntu 24.04 LTS x86_64 in a docker container the test for process already terminated is failing as written in https://github.com/TartanLlama/sdb/blob/chapter-4/test/tests.cpp#L63-L68. If I change it to move the `REQUIRE_THROWS_AS` directly after the resume call then it passes. e.g.

```C++
TEST_CASE("process::resume already terminated", "[process]") {
    auto proc = process::launch("./build/test/targets/end_immediately");
    proc->resume();
    REQUIRE_THROWS_AS(proc->resume(), error);
}
```

Thank you for writing such an enjoyable book. I'm having a blast working through the C++ and adapting parts of it to run on ARM64 / macOS.

**Comment by TartanLlama** [comment]
Thanks for getting in touch! Is this an x64 Ubuntu Docker container running on Mac? It seems there's some issues with Docker on Mac #3 . Do you get the same results running through a [UTM VM](https://mac.getutm.app/)?

**Comment by tmcgilchrist** [comment]
Yes this is running an Ubuntu x86_64 Docker container on an ARM64 Mac. I haven't tried on UTM VM yet but I will.
On bare metal Ubuntu 24.04 x86_64 the tests work fine. 

I don't know how `REQUIRE_THROWS_AS` is implemented, perhaps the Rosetta emulation is causing a problem?

**Comment by tmcgilchrist** [comment]
Working through more of the book into Chapter 6 reading/writing registers using ptrace does not work with any configuration of Docker for Mac on Apple Silicon. Trying to get it working with emulation seems to require QEMU directly or UTM VM. I've given up on this configuration and have switched to an x86_64 Mac with Docker that thankfully works fine. 

The original code works on this setup without modifications. So this Errata can be closed and serve as a warning for others ☠️

**Comment by TartanLlama** [comment]
Thanks for following up, I'm going to add some text to the intro of the book about this
