### ISSUE TITLE
Missing increase of depth in recursive call inside visualize_class_type

### ISSUE THREAD

**Issue by yharaskrik42** [TartanLlama/sdb#5]
https://github.com/TartanLlama/sdb/blob/f38f948e1e753fe051a8b45d35c72edbf1f5efff/src/type.cpp#L98

shouldn't it be depth+1?
`                auto member_str = data.visualize(proc, depth + 1);
`

**Comment by TartanLlama** [comment]
Fixed in 63341e04e0387a1f62c05cf8f6caa16c26917ca0
