### ISSUE TITLE
Errata: libedit not found error

### ISSUE THREAD

**Issue by skytwosea** [TartanLlama/sdb#6]
**Chapter: 1**
**Description: libedit not found error**
**Reproduction steps: transcribe code from early-release print up to page 8, end of `Dependency Management with vcpkg` section**
**Solution: sudo apt install libedit-dev**

I'm not sure if this is the right place for this sort of note. The bottom paragraph on p 7 says:
> Now, configuring CMake will build and install _libedit_ into a project-local directory.
However, on my system, `libedit` was not found and had to be installed via `apt.`

I am not very familiar with C++, so am unsure if I just missed something, or if the text omits a step?

my system:
- kernel 6.8.0-51-generic
- cmake 3.28.3
- pkg-config 1.8.1

Code transcribed and checked for typos. When running `cmake --build .`, the following error is raised:
```
$ cmake --build .
-- Checking for module 'libedit'
--   Package 'libedit', required by 'virtual:world', not found
CMake Error at /usr/share/cmake-3.28/Modules/FindPkgConfig.cmake:619 (message):
  The following required packages were not found:

   - libedit

Call Stack (most recent call first):
  /usr/share/cmake-3.28/Modules/FindPkgConfig.cmake:841 (_pkg_check_modules_internal)
  CMakeLists.txt:6 (pkg_check_modules)


-- Configuring incomplete, errors occurred!
gmake: *** [Makefile:618: cmake_check_build_system] Error 1
$
```

MY SOLUTION:
`apt install libedit-dev`

RESULT:
Things appear to be working now:
```
$ cmake --build .
-- Checking for module 'libedit'
--   Found libedit, version 3.1
-- Configuring done (0.1s)
-- Generating done (0.0s)
-- Build files have been written to: /home/vesper/Dropbox/dev/building_a_debugger/sdb
[ 50%] Built target libsdb
[ 75%] Building CXX object tools/CMakeFiles/sdb.dir/sdb.cpp.o
[100%] Linking CXX executable sdb
[100%] Built target sdb
$ ./tools/sdb
Hello, sdb!
$
```

further confirmation with `cmake --fresh .` : 
```
-- The CXX compiler identification is GNU 13.3.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.8.1") 
-- Checking for module 'libedit'
--   Found libedit, version 3.1
-- Configuring done (0.4s)
-- Generating done (0.0s)
-- Build files have been written to: /home/vesper/Dropbox/dev/building_a_debugger/sdb
```

**Comment by TartanLlama** [comment]
Thanks for getting in touch! The dependency should be fulfilled by vcpkg if
you're following the instructions exactly. Have you set up vcpkg? Or are
you intentionally not using it?
Sy

**Comment by skytwosea** [comment]
I must be missing something re: `vcpkg`; I just ran into the same problem with `catch2`. I'll review what I've done so far w.r.t. `vcpkg` and let you know. Thanks!

**Comment by TartanLlama** [comment]
Sure! I would make sure you supply the correct path for
-DCMAKE_TOOLCHAIN_FILE and that the vcpkg.json file is in the root of your
directory, at the same level as the root CMakeLists.txt

**Comment by skytwosea** [comment]
That was just the problem; I hadn't removed the cache file first and so the -DCMAKE... call didn't work. It's fixed now, and I think the problem re: vcpkg, catch2, and libedit is solved. Thanks again!

I've run into another error:
```
Target "tests" links to:
  sdb::libsdb
but the target was not found.
```

I'm trying to track down any potential typos etc., should have it sorted soon.

**Comment by skytwosea** [comment]
@TartanLlama thanks again for dropping in. I got myself sorted; first issue was a silly typo, and the second issue is that I am not familiar with cmake/make.

My day job revolves around Python, a bit of SQL, and a bit of bash/zsh. I've spent quite a bit of hobby time with Zig and less with Rust. I know just enough C to read source, but C++ and the entire dev environment context is very new to me. Perhaps its a bit insane but I'm intending to use your book, and the recommended crash course, to learn C++ as well as explore how debuggers work.

I was bashing my head against the wall trying to figure out why `cmake` wasn't producing an executable, why the catch2 configuration files were sometimes being reported as missing... then I ran make and the world shifted back into focus. Looks like I have some reading to do!

Long term goal is to translate `sdb` into Rust and/or Zig, once I've finished the c++ implementation. I am thoroughly enjoying what I'm reading so far, and am learning a ton. This is a massive effort on your part, and I appreciate it immensely!

Do you run or know of a forum for questions for folk who are working through this book? Discord, Mastodon, Reddit? I'd love to be able to find a community to work through this together.

Thanks again, and happy holidays!

**Comment by TartanLlama** [comment]
I'm glad you're enjoying it! I know some other folks are running through it
in Rust and Zig. I don't know about public groups working through the book,
but feel free to get in touch here if you get stuck!
