### ISSUE TITLE
Errata: Possible typo in Chapter 6

### ISSUE THREAD

**Issue by WenqingZong** [TartanLlama/sdb#7]
**Chapter:** 6
**Description:** Possible typo https://github.com/TartanLlama/sdb/blob/881d145832bb46d22d1208eb2c8ca2ced16d0947/tools/sdb.cpp#L194-L195 I have a feeling this line should be inside the `catch` block, otherwise we send an error regardless if parsing success.
**Reproduction steps:** N/A

**Comment by TartanLlama** [comment]
Thanks for getting in touch! It's intentionally outside of the block,
because the valid cases all return early, so control flow shouldn't reach
that line.

**Comment by WenqingZong** [comment]
Thanks for the fast reply, I'll close the issue then!
